# GWEI CONTROL
MAX_GAS = 25

# TAKE THE WALLETS IN RANDOM ORDER
RANDOM_WALLETS = True

# FOR ERRORS REVIEW
DEBUG_MODE = False

# STARKNET NODE, YOU CAN CHANGE THIS
STARKNET_NODE = 'https://starknet-mainnet.public.blastapi.io'

# THREADS CONTROLS
QUANTITY_THREADS = 1
THREAD_SLEEP_FROM = 15 # Seconds
THREAD_SLEEP_TO = 30 # Seconds

# SLEEPS AFTER WORK
SLEEP_AFTER_WORK_FROM = 60 # Seconds
SLEEP_AFTER_WORK_TO = 90 # Seconds

# SLIPPAGE FOR SWAPS
SLIPPAGE = 3